export const islamicFacts: string[] = [
  'The Quran was revealed over a period of 23 years.',
  'There are 114 Surahs (chapters) in the Quran.',
  'Surah Al-Fatiha is recited in every unit of prayer (Salah).',
  'The longest Surah is Al-Baqarah and the shortest is Al-Kawthar.',
  'The first revelation began with the word "Read" (Iqra).',
  'The Quran is divided into 30 Juz for easier reading.',
  'The Kaaba is located in Masjid al-Haram in Makkah.',
  'The Qiblah is the direction Muslims face during prayer.',
  'The Islamic calendar is lunar and has 12 months.',
  'Ramadan is the ninth month of the Islamic calendar.',
  'Laylat al-Qadr is better than a thousand months.',
  'The five daily prayers are Fajr, Dhuhr, Asr, Maghrib, and Isha.',
  'Wudu is the ritual purification before prayer.',
  'Jumuah is the congregational Friday prayer.',
  'Zakat is a compulsory charity for eligible Muslims.',
  'Sadaqah is voluntary charity beyond Zakat.',
  'Hajj is an obligation once in a lifetime for those who are able.',
  'Umrah can be performed any time of the year.',
  'The Adhan is the call to prayer.',
  'Iqamah is the second call right before prayer starts.',
  'The first Hijrah was the migration from Makkah to Madinah.',
  'The Prophet Muhammad (PBUH) was born in the Year of the Elephant.',
  'The Prophet Muhammad (PBUH) was known as Al-Amin (the Trustworthy).',
  'The Quran was compiled into a single mushaf during Caliph Uthman\'s time.',
  'Surah Yasin is often called the heart of the Quran.',
  'Surah Al-Ikhlas affirms pure monotheism (Tawhid).',
  'Tawhid means the oneness of Allah.',
  'Shirk is associating partners with Allah and is the gravest sin.',
  'Islam teaches intention (niyyah) in every act of worship.',
  'Dhikr is the remembrance of Allah.',
  'Tasbih is often said as SubhanAllah (Glory be to Allah).',
  'Tahmid is saying Alhamdulillah (All praise is for Allah).',
  'Takbir is saying Allahu Akbar (Allah is the Greatest).',
  'The Prophet (PBUH) said the best among you are those who learn the Quran and teach it.',
  'The Quran was revealed in the Arabic language.',
  'The first Surah revealed was Al-Alaq (96).',
  'The last Surah revealed was An-Nasr (110).',
  'Masjid al-Aqsa is the third holiest mosque in Islam.',
  'Masjid an-Nabawi is the Prophet\'s mosque in Madinah.',
  'The Kaaba was built by Prophet Ibrahim and Prophet Ismail.',
  'Zamzam water has flowed for centuries without drying up.',
  'The word "Islam" comes from the root meaning peace and submission.',
  'The word "Quran" means "recitation" in Arabic.',
  'The Quran contains guidance, mercy, and healing for believers.',
  'The Sahaba were the companions of the Prophet (PBUH).',
  'The Khulafa ar-Rashidun were the four rightly guided caliphs.',
  'Abu Bakr was the first caliph after the Prophet (PBUH).',
  'Umar ibn al-Khattab established a formal Islamic calendar.',
  'Uthman ibn Affan standardized the Quranic mushaf.',
  'Ali ibn Abi Talib was known for knowledge and bravery.',
  'The Prophet (PBUH) taught that deeds are judged by intentions.',
  'Islam encourages seeking knowledge from cradle to grave.',
  'Backbiting (ghibah) is prohibited in Islam.',
  'The Quran warns against arrogance and pride.',
  'Salah is the second pillar of Islam.',
  'The Shahada is the testimony of faith.',
  'Fasting in Ramadan is the fourth pillar of Islam.',
  'Zakat is the third pillar of Islam.',
  'Hajj is the fifth pillar of Islam.',
  'The Quran mentions many prophets, including Adam, Nuh, Ibrahim, Musa, and Isa.',
  'Prophet Isa is Jesus in Islam and is highly honored.',
  'Prophet Musa is Moses in Islam.',
  'Prophet Nuh is Noah in Islam.',
  'Prophet Ibrahim is Abraham in Islam.',
  'Prophet Yusuf is Joseph in Islam.',
  'Prophet Yunus is Jonah in Islam.',
  'The Quran emphasizes justice and kindness.',
  'Islam commands honoring parents.',
  'Maintaining family ties is highly encouraged.',
  'The Quran encourages truthful speech.',
  'The Prophet (PBUH) encouraged smiling as charity.',
  'Giving water is among the best forms of charity.',
  'Friday is the most special day of the week in Islam.',
  'The Friday prayer includes a sermon (khutbah).',
  'The last ten nights of Ramadan are especially blessed.',
  'Itikaf is seclusion in the mosque during the last ten nights.',
  'The Quran describes itself as guidance for mankind.',
  'Surah Al-Baqarah is the longest Surah in the Quran.',
  'Ayat al-Kursi is in Surah Al-Baqarah (2:255).',
  'Surah Al-Kahf is encouraged to read on Fridays.',
  'The Quran was memorized by many companions during the Prophet\'s life.',
  'The Prophet (PBUH) forbade harming neighbors.',
  'Halal means permissible; haram means forbidden.',
  'Islam forbids interest (riba).',
  'Honesty in trade is emphasized in Islam.',
  'The Prophet (PBUH) praised those who are gentle and patient.',
  'Islam encourages moderation in all things.',
  'The Quran teaches that every soul will taste death.',
  'The Day of Judgment is a core belief in Islam.',
  'Angels are part of the unseen in Islamic belief.',
  'Jibreel (Gabriel) brought revelation to the Prophet (PBUH).',
  'Mikail (Michael) is an angel mentioned in Islamic belief.',
  'Israfil is associated with the blowing of the trumpet.',
  'Malik is the guardian of Hell in Islamic tradition.',
  'The Quran encourages gratitude in all circumstances.',
  'Patience (sabr) is mentioned many times in the Quran.',
  'The Prophet (PBUH) emphasized kindness to animals.',
  'Islam forbids oppression and wrongdoing (zulm).',
  'The Quran calls believers to be truthful witnesses.',
  'Making dua is a form of worship.',
  'The Prophet (PBUH) taught that the best charity is in secret.',
  'The Quran was revealed in portions to strengthen hearts.',
  'The Quran is memorized by millions worldwide.',
  'The word "Allah" is the Arabic name for God.',
  'Islam teaches that Allah is One, with no partners.',
  'The Prophet (PBUH) encouraged visiting the sick.',
  'Islam promotes cleanliness and hygiene.',
  'The miswak is a traditional tooth-cleaning stick used by the Prophet (PBUH).',
  'The Prophet (PBUH) said the strong believer is better than the weak believer.',
  'Seeking forgiveness (istighfar) is highly encouraged.',
  'The Quran warns against envy and hatred.',
  'Islam encourages reconciliation between people.',
  'The best of people are those who benefit others most.',
  'The Quran teaches balance between hope and fear of Allah.',
  'The Prophet (PBUH) said that Allah loves consistent small deeds.',
  'The Quran teaches that charity never decreases wealth.',
  'The Prophet (PBUH) loved to break fast with dates and water.',
  'Islam encourages feeding the hungry.',
  'The Prophet (PBUH) emphasized mercy and compassion.',
  'The Quran describes believers as those who establish prayer and give charity.',
  'Surah Al-Fil recounts the story of the Year of the Elephant.',
  'Surah Al-Asr teaches the value of time.',
  'Surah Al-Mulk is encouraged to read at night.',
  'The Prophet (PBUH) recommended reading the last two verses of Al-Baqarah at night.',
  'The Quran describes Paradise as gardens under which rivers flow.',
  'The Quran warns against unjustly consuming wealth.',
  'The Prophet (PBUH) said that actions are judged by intentions.',
  'The Quran calls believers to be patient and steadfast.',
  'The Prophet (PBUH) encouraged greeting with peace (salam).',
  'The Quran mentions that Allah is the Most Merciful (Ar-Rahman).',
  'Islam teaches that repentance wipes away sins.',
  'The Prophet (PBUH) said that the best speech is the Quran.',
];
