/**
 * Complete list of all 114 Surahs of the Quran
 */

export interface Surah {
  number: number;
  name: string;
  arabicName: string;
  meaning: string;
  verses: number;
  revelation: 'Meccan' | 'Madinan';
  description: string;
}

export const allSurahs: Surah[] = [
  { number: 1, name: 'Al-Fatiha', arabicName: 'الفاتحة', meaning: 'The Opening', verses: 7, revelation: 'Meccan', description: 'The opening chapter of the Quran, recited in every prayer' },
  { number: 2, name: 'Al-Baqarah', arabicName: 'البقرة', meaning: 'The Cow', verses: 286, revelation: 'Madinan', description: 'The longest chapter, containing guidance on various aspects of Islamic life' },
  { number: 3, name: 'Al-Imran', arabicName: 'آل عمران', meaning: 'The Family of Imran', verses: 200, revelation: 'Madinan', description: 'Discusses the family of Imran and the story of Maryam' },
  { number: 4, name: 'An-Nisa', arabicName: 'النساء', meaning: 'The Women', verses: 176, revelation: 'Madinan', description: 'Addresses women\'s rights and family matters' },
  { number: 5, name: 'Al-Maidah', arabicName: 'المائدة', meaning: 'The Table Spread', verses: 120, revelation: 'Madinan', description: 'Discusses halal food, contracts, and judicial matters' },
  { number: 6, name: 'Al-Anam', arabicName: 'الأنعام', meaning: 'The Cattle', verses: 165, revelation: 'Meccan', description: 'Affirms Allah\'s attributes and oneness' },
  { number: 7, name: 'Al-Araf', arabicName: 'الأعراف', meaning: 'The Heights', verses: 206, revelation: 'Meccan', description: 'Stories of prophets and warnings' },
  { number: 8, name: 'Al-Anfal', arabicName: 'الأنفال', meaning: 'The Spoils of War', verses: 75, revelation: 'Madinan', description: 'Guidelines on warfare and distribution of spoils' },
  { number: 9, name: 'At-Tawbah', arabicName: 'التوبة', meaning: 'The Repentance', verses: 129, revelation: 'Madinan', description: 'Discusses treaties, warfare, and hypocrisy' },
  { number: 10, name: 'Yunus', arabicName: 'يونس', meaning: 'Jonah', verses: 109, revelation: 'Meccan', description: 'The story of Prophet Yunus' },
  { number: 11, name: 'Hud', arabicName: 'هود', meaning: 'Hud', verses: 123, revelation: 'Meccan', description: 'Stories of Prophet Hud and other prophets' },
  { number: 12, name: 'Yusuf', arabicName: 'يوسف', meaning: 'Joseph', verses: 111, revelation: 'Meccan', description: 'The complete story of Prophet Yusuf' },
  { number: 13, name: 'Ar-Rad', arabicName: 'الرعد', meaning: 'The Thunder', verses: 43, revelation: 'Madinan', description: 'Allah\'s power displayed in nature' },
  { number: 14, name: 'Ibrahim', arabicName: 'إبراهيم', meaning: 'Abraham', verses: 52, revelation: 'Meccan', description: 'Story of Prophet Ibrahim' },
  { number: 15, name: 'Al-Hijr', arabicName: 'الحجر', meaning: 'The Rocky Track', verses: 99, revelation: 'Meccan', description: 'Warnings to disbelievers' },
  { number: 16, name: 'An-Nahl', arabicName: 'النحل', meaning: 'The Bee', verses: 128, revelation: 'Meccan', description: 'Allah\'s blessings in nature' },
  { number: 17, name: 'Al-Isra', arabicName: 'الإسراء', meaning: 'The Night Journey', verses: 111, revelation: 'Meccan', description: 'The Prophet\'s night journey' },
  { number: 18, name: 'Al-Kahf', arabicName: 'الكهف', meaning: 'The Cave', verses: 110, revelation: 'Meccan', description: 'Story of the people of the cave' },
  { number: 19, name: 'Maryam', arabicName: 'مريم', meaning: 'Mary', verses: 98, revelation: 'Meccan', description: 'Story of Maryam and Prophet Isa' },
  { number: 20, name: 'Ta-Ha', arabicName: 'طه', meaning: 'Ta-Ha', verses: 135, revelation: 'Meccan', description: 'Story of Prophet Musa' },
  { number: 21, name: 'Al-Anbya', arabicName: 'الأنبياء', meaning: 'The Prophets', verses: 112, revelation: 'Meccan', description: 'Stories of various prophets' },
  { number: 22, name: 'Al-Hajj', arabicName: 'الحج', meaning: 'The Pilgrimage', verses: 78, revelation: 'Madinan', description: 'Rites and significance of Hajj' },
  { number: 23, name: 'Al-Muminun', arabicName: 'المؤمنون', meaning: 'The Believers', verses: 118, revelation: 'Meccan', description: 'Characteristics of true believers' },
  { number: 24, name: 'An-Nur', arabicName: 'النور', meaning: 'The Light', verses: 64, revelation: 'Madinan', description: 'Social and moral guidance' },
  { number: 25, name: 'Al-Furqan', arabicName: 'الفرقان', meaning: 'The Criterion', verses: 77, revelation: 'Meccan', description: 'Distinction between truth and falsehood' },
  { number: 26, name: 'Ash-Shuara', arabicName: 'الشعراء', meaning: 'The Poets', verses: 227, revelation: 'Meccan', description: 'Stories of various prophets' },
  { number: 27, name: 'An-Naml', arabicName: 'النمل', meaning: 'The Ant', verses: 93, revelation: 'Meccan', description: 'Story of Prophet Sulayman and Queen of Sheba' },
  { number: 28, name: 'Al-Qasas', arabicName: 'القصص', meaning: 'The Stories', verses: 88, revelation: 'Meccan', description: 'Life of Prophet Musa in detail' },
  { number: 29, name: 'Al-Ankabut', arabicName: 'العنكبوت', meaning: 'The Spider', verses: 69, revelation: 'Meccan', description: 'Tests and trials of faith' },
  { number: 30, name: 'Ar-Rum', arabicName: 'الروم', meaning: 'The Romans', verses: 60, revelation: 'Meccan', description: 'The prophecy about Romans' },
  { number: 31, name: 'Luqman', arabicName: 'لقمان', meaning: 'Luqman', verses: 34, revelation: 'Meccan', description: 'The wisdom of Luqman' },
  { number: 32, name: 'As-Sajdah', arabicName: 'السجدة', meaning: 'The Prostration', verses: 30, revelation: 'Meccan', description: 'Signs of Allah in creation' },
  { number: 33, name: 'Al-Ahzab', arabicName: 'الأحزاب', meaning: 'The Combined Forces', verses: 73, revelation: 'Madinan', description: 'The Battle of the Trench' },
  { number: 34, name: 'Saba', arabicName: 'سبإ', meaning: 'Sheba', verses: 54, revelation: 'Meccan', description: 'Story of the people of Sheba' },
  { number: 35, name: 'Fatir', arabicName: 'فاطر', meaning: 'The Originator', verses: 45, revelation: 'Meccan', description: 'Allah as the Creator' },
  { number: 36, name: 'Ya-Sin', arabicName: 'يس', meaning: 'Ya-Sin', verses: 83, revelation: 'Meccan', description: 'The heart of the Quran' },
  { number: 37, name: 'As-Saffat', arabicName: 'الصافات', meaning: 'Those Ranged in Ranks', verses: 182, revelation: 'Meccan', description: 'Stories of prophets and resurrection' },
  { number: 38, name: 'Sad', arabicName: 'ص', meaning: 'Sad', verses: 88, revelation: 'Meccan', description: 'Story of Prophet Dawud and Sulayman' },
  { number: 39, name: 'Az-Zumar', arabicName: 'الزمر', meaning: 'The Groups', verses: 75, revelation: 'Meccan', description: 'Groups in Paradise and Hell' },
  { number: 40, name: 'Ghafir', arabicName: 'غافر', meaning: 'The Forgiver', verses: 85, revelation: 'Meccan', description: 'Allah\'s forgiveness and mercy' },
  { number: 41, name: 'Fussilat', arabicName: 'فصلت', meaning: 'Explained in Detail', verses: 54, revelation: 'Meccan', description: 'Signs of Allah in creation' },
  { number: 42, name: 'Ash-Shura', arabicName: 'الشورى', meaning: 'The Consultation', verses: 53, revelation: 'Meccan', description: 'Consultation in community affairs' },
  { number: 43, name: 'Az-Zukhruf', arabicName: 'الزخرف', meaning: 'The Gold Adornments', verses: 89, revelation: 'Meccan', description: 'Materialism vs faith' },
  { number: 44, name: 'Ad-Dukhan', arabicName: 'الدخان', meaning: 'The Smoke', verses: 59, revelation: 'Meccan', description: 'The Day of Judgment' },
  { number: 45, name: 'Al-Jathiyah', arabicName: 'الجاثية', meaning: 'The Kneeling', verses: 37, revelation: 'Meccan', description: 'All will kneel on Judgment Day' },
  { number: 46, name: 'Al-Ahqaf', arabicName: 'الأحقاف', meaning: 'The Wind-Curved Sandhills', verses: 35, revelation: 'Meccan', description: 'Story of Prophet Hud' },
  { number: 47, name: 'Muhammad', arabicName: 'محمد', meaning: 'Muhammad', verses: 38, revelation: 'Madinan', description: 'Guidance for believers' },
  { number: 48, name: 'Al-Fath', arabicName: 'الفتح', meaning: 'The Victory', verses: 29, revelation: 'Madinan', description: 'Treaty of Hudaybiyyah' },
  { number: 49, name: 'Al-Hujurat', arabicName: 'الحجرات', meaning: 'The Rooms', verses: 18, revelation: 'Madinan', description: 'Social etiquette in Islam' },
  { number: 50, name: 'Qaf', arabicName: 'ق', meaning: 'Qaf', verses: 45, revelation: 'Meccan', description: 'Resurrection and accountability' },
  { number: 51, name: 'Adh-Dhariyat', arabicName: 'الذاريات', meaning: 'The Winnowing Winds', verses: 60, revelation: 'Meccan', description: 'Signs in nature' },
  { number: 52, name: 'At-Tur', arabicName: 'الطور', meaning: 'The Mount', verses: 49, revelation: 'Meccan', description: 'Mount Sinai and the Day of Judgment' },
  { number: 53, name: 'An-Najm', arabicName: 'النجم', meaning: 'The Star', verses: 62, revelation: 'Meccan', description: 'The Prophet\'s ascension' },
  { number: 54, name: 'Al-Qamar', arabicName: 'القمر', meaning: 'The Moon', verses: 55, revelation: 'Meccan', description: 'The splitting of the moon' },
  { number: 55, name: 'Ar-Rahman', arabicName: 'الرحمن', meaning: 'The Most Merciful', verses: 78, revelation: 'Madinan', description: 'Allah\'s countless blessings' },
  { number: 56, name: 'Al-Waqiah', arabicName: 'الواقعة', meaning: 'The Inevitable', verses: 96, revelation: 'Meccan', description: 'The Day of Judgment' },
  { number: 57, name: 'Al-Hadid', arabicName: 'الحديد', meaning: 'The Iron', verses: 29, revelation: 'Madinan', description: 'Spending in Allah\'s way' },
  { number: 58, name: 'Al-Mujadila', arabicName: 'المجادلة', meaning: 'The Pleading Woman', verses: 22, revelation: 'Madinan', description: 'Woman who argued about her husband' },
  { number: 59, name: 'Al-Hashr', arabicName: 'الحشر', meaning: 'The Exile', verses: 24, revelation: 'Madinan', description: 'Exile of a Jewish tribe' },
  { number: 60, name: 'Al-Mumtahanah', arabicName: 'الممتحنة', meaning: 'She That is to be Examined', verses: 13, revelation: 'Madinan', description: 'Testing believers\' faith' },
  { number: 61, name: 'As-Saf', arabicName: 'الصف', meaning: 'The Ranks', verses: 14, revelation: 'Madinan', description: 'Standing firm in ranks' },
  { number: 62, name: 'Al-Jumuah', arabicName: 'الجمعة', meaning: 'Friday', verses: 11, revelation: 'Madinan', description: 'Friday prayer obligations' },
  { number: 63, name: 'Al-Munafiqun', arabicName: 'المنافقون', meaning: 'The Hypocrites', verses: 11, revelation: 'Madinan', description: 'Characteristics of hypocrites' },
  { number: 64, name: 'At-Taghabun', arabicName: 'التغابن', meaning: 'The Mutual Loss & Gain', verses: 18, revelation: 'Madinan', description: 'Day of loss and gain' },
  { number: 65, name: 'At-Talaq', arabicName: 'الطلاق', meaning: 'The Divorce', verses: 12, revelation: 'Madinan', description: 'Rules regarding divorce' },
  { number: 66, name: 'At-Tahrim', arabicName: 'التحريم', meaning: 'The Prohibition', verses: 12, revelation: 'Madinan', description: 'Domestic matters of the Prophet' },
  { number: 67, name: 'Al-Mulk', arabicName: 'الملك', meaning: 'The Sovereignty', verses: 30, revelation: 'Meccan', description: 'Allah\'s dominion over all' },
  { number: 68, name: 'Al-Qalam', arabicName: 'القلم', meaning: 'The Pen', verses: 52, revelation: 'Meccan', description: 'The pen and divine revelation' },
  { number: 69, name: 'Al-Haqqah', arabicName: 'الحاقة', meaning: 'The Reality', verses: 52, revelation: 'Meccan', description: 'The inevitable reality' },
  { number: 70, name: 'Al-Maarij', arabicName: 'المعارج', meaning: 'The Ascending Stairways', verses: 44, revelation: 'Meccan', description: 'Ascension to Allah' },
  { number: 71, name: 'Nuh', arabicName: 'نوح', meaning: 'Noah', verses: 28, revelation: 'Meccan', description: 'Prophet Nuh\'s call to his people' },
  { number: 72, name: 'Al-Jinn', arabicName: 'الجن', meaning: 'The Jinn', verses: 28, revelation: 'Meccan', description: 'Jinn listening to the Quran' },
  { number: 73, name: 'Al-Muzzammil', arabicName: 'المزمل', meaning: 'The Enshrouded One', verses: 20, revelation: 'Meccan', description: 'Night prayers and devotion' },
  { number: 74, name: 'Al-Muddaththir', arabicName: 'المدثر', meaning: 'The Cloaked One', verses: 56, revelation: 'Meccan', description: 'Early warning to Makkah' },
  { number: 75, name: 'Al-Qiyamah', arabicName: 'القيامة', meaning: 'The Resurrection', verses: 40, revelation: 'Meccan', description: 'Day of Resurrection' },
  { number: 76, name: 'Al-Insan', arabicName: 'الإنسان', meaning: 'The Man', verses: 31, revelation: 'Madinan', description: 'Creation and reward of man' },
  { number: 77, name: 'Al-Mursalat', arabicName: 'المرسلات', meaning: 'The Emissaries', verses: 50, revelation: 'Meccan', description: 'Winds sent forth' },
  { number: 78, name: 'An-Naba', arabicName: 'النبإ', meaning: 'The Tidings', verses: 40, revelation: 'Meccan', description: 'The great news' },
  { number: 79, name: 'An-Naziat', arabicName: 'النازعات', meaning: 'Those Who Drag Forth', verses: 46, revelation: 'Meccan', description: 'Angels who extract souls' },
  { number: 80, name: 'Abasa', arabicName: 'عبس', meaning: 'He Frowned', verses: 42, revelation: 'Meccan', description: 'The blind man and the Prophet' },
  { number: 81, name: 'At-Takwir', arabicName: 'التكوير', meaning: 'The Overthrowing', verses: 29, revelation: 'Meccan', description: 'Cosmic events of the Last Day' },
  { number: 82, name: 'Al-Infitar', arabicName: 'الإنفطار', meaning: 'The Cleaving', verses: 19, revelation: 'Meccan', description: 'The sky splitting apart' },
  { number: 83, name: 'Al-Mutaffifin', arabicName: 'المطففين', meaning: 'The Defrauding', verses: 36, revelation: 'Meccan', description: 'Warning against cheating in trade' },
  { number: 84, name: 'Al-Inshiqaq', arabicName: 'الإنشقاق', meaning: 'The Splitting Open', verses: 25, revelation: 'Meccan', description: 'The heavens splitting open' },
  { number: 85, name: 'Al-Buruj', arabicName: 'البروج', meaning: 'The Mansions of the Stars', verses: 22, revelation: 'Meccan', description: 'The constellations' },
  { number: 86, name: 'At-Tariq', arabicName: 'الطارق', meaning: 'The Nightcomer', verses: 17, revelation: 'Meccan', description: 'The piercing star' },
  { number: 87, name: 'Al-Ala', arabicName: 'الأعلى', meaning: 'The Most High', verses: 19, revelation: 'Meccan', description: 'Glorification of the Most High' },
  { number: 88, name: 'Al-Ghashiyah', arabicName: 'الغاشية', meaning: 'The Overwhelming', verses: 26, revelation: 'Meccan', description: 'The overwhelming event' },
  { number: 89, name: 'Al-Fajr', arabicName: 'الفجر', meaning: 'The Dawn', verses: 30, revelation: 'Meccan', description: 'The dawn and ancient peoples' },
  { number: 90, name: 'Al-Balad', arabicName: 'البلد', meaning: 'The City', verses: 20, revelation: 'Meccan', description: 'The city of Makkah' },
  { number: 91, name: 'Ash-Shams', arabicName: 'الشمس', meaning: 'The Sun', verses: 15, revelation: 'Meccan', description: 'The sun and purification of soul' },
  { number: 92, name: 'Al-Layl', arabicName: 'الليل', meaning: 'The Night', verses: 21, revelation: 'Meccan', description: 'The night and charity' },
  { number: 93, name: 'Ad-Duhaa', arabicName: 'الضحى', meaning: 'The Morning Hours', verses: 11, revelation: 'Meccan', description: 'Comfort to the Prophet' },
  { number: 94, name: 'Ash-Sharh', arabicName: 'الشرح', meaning: 'The Consolation', verses: 8, revelation: 'Meccan', description: 'Expansion of the chest' },
  { number: 95, name: 'At-Tin', arabicName: 'التين', meaning: 'The Fig', verses: 8, revelation: 'Meccan', description: 'The fig and the olive' },
  { number: 96, name: 'Al-Alaq', arabicName: 'العلق', meaning: 'The Clot', verses: 19, revelation: 'Meccan', description: 'First revelation' },
  { number: 97, name: 'Al-Qadr', arabicName: 'القدر', meaning: 'The Power', verses: 5, revelation: 'Meccan', description: 'The Night of Decree' },
  { number: 98, name: 'Al-Bayyinah', arabicName: 'البينة', meaning: 'The Clear Proof', verses: 8, revelation: 'Madinan', description: 'The clear evidence' },
  { number: 99, name: 'Az-Zalzalah', arabicName: 'الزلزلة', meaning: 'The Earthquake', verses: 8, revelation: 'Madinan', description: 'The earth quaking' },
  { number: 100, name: 'Al-Adiyat', arabicName: 'العاديات', meaning: 'The Courserrs', verses: 11, revelation: 'Meccan', description: 'The charging horses' },
  { number: 101, name: 'Al-Qariah', arabicName: 'القارعة', meaning: 'The Calamity', verses: 11, revelation: 'Meccan', description: 'The striking calamity' },
  { number: 102, name: 'At-Takathur', arabicName: 'التكاثر', meaning: 'The Rivalry in Worldly Increase', verses: 8, revelation: 'Meccan', description: 'Competition for more' },
  { number: 103, name: 'Al-Asr', arabicName: 'العصر', meaning: 'The Declining Day', verses: 3, revelation: 'Meccan', description: 'By time, man is in loss' },
  { number: 104, name: 'Al-Humazah', arabicName: 'الهمزة', meaning: 'The Traducer', verses: 9, revelation: 'Meccan', description: 'The slanderer' },
  { number: 105, name: 'Al-Fil', arabicName: 'الفيل', meaning: 'The Elephant', verses: 5, revelation: 'Meccan', description: 'The elephant army' },
  { number: 106, name: 'Quraysh', arabicName: 'قريش', meaning: 'Quraysh', verses: 4, revelation: 'Meccan', description: 'The Quraysh tribe' },
  { number: 107, name: 'Al-Maun', arabicName: 'الماعون', meaning: 'The Small Kindnesses', verses: 7, revelation: 'Meccan', description: 'Small acts of kindness' },
  { number: 108, name: 'Al-Kawthar', arabicName: 'الكوثر', meaning: 'The Abundance', verses: 3, revelation: 'Meccan', description: 'Abundance given to the Prophet' },
  { number: 109, name: 'Al-Kafirun', arabicName: 'الكافرون', meaning: 'The Disbelievers', verses: 6, revelation: 'Meccan', description: 'To you your religion, to me mine' },
  { number: 110, name: 'An-Nasr', arabicName: 'النصر', meaning: 'The Divine Support', verses: 3, revelation: 'Madinan', description: 'Allah\'s help and victory' },
  { number: 111, name: 'Al-Masad', arabicName: 'المسد', meaning: 'The Palm Fiber', verses: 5, revelation: 'Meccan', description: 'Abu Lahab\'s punishment' },
  { number: 112, name: 'Al-Ikhlas', arabicName: 'الإخلاص', meaning: 'The Sincerity', verses: 4, revelation: 'Meccan', description: 'Pure monotheism' },
  { number: 113, name: 'Al-Falaq', arabicName: 'الفلق', meaning: 'The Daybreak', verses: 5, revelation: 'Meccan', description: 'Seeking refuge from evil' },
  { number: 114, name: 'An-Nas', arabicName: 'الناس', meaning: 'Mankind', verses: 6, revelation: 'Meccan', description: 'Seeking refuge in the Lord of mankind' },
];
